liip_imagine:
    default_filter_set_settings:
        format: webp
    webp:
        generate: true
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"
