# Remove if you don't use SyliusAdminBundle
sylius_return_admin:
    resource: "@SyliusReturnPlugin/config/admin_routing.yaml"
    prefix: '/%sylius_admin.path_name%'

# Remove if you don't use SyliusShopBundle
sylius_return_shop:
    resource: "@SyliusReturnPlugin/config/shop_routing.yaml"
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$
