# Remove if you don't use SyliusShopBundle
sylius_loyalty_shop:
    resource: "@SyliusLoyaltyPlugin/config/shop_routing.yaml"
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$
