sylius_paypal_webhook:
    resource: "@SyliusPayPalPlugin/Resources/config/webhook_routing.yaml"

sylius_one_page_checkout:
    resource: "@SyliusOnePageCheckoutPlugin/config/routing.yml"
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

sylius_shop_checkout:
    resource: "@SyliusShopBundle/Resources/config/routing/checkout.yml"
    condition: false

sylius_shop_checkout_complete:
    path: /{_locale}/checkout
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

sylius_shop_checkout_start:
    path: /{_locale}/checkout
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$
